name: "FlightManagement"
main: "ml.mackenziemolloy.flightmanagement.Main"
author: "Mackenzie Molloy"
version: "1.0"
apt-version: "1.15"
commands:
  fly:
    aliases: [flight, flightmanagement]
    description: Main command
